server:
  host: hexa-a 
  port: 5000
  
database:
  db: hexa-a-db
  host: mongodb
  port: 27017
  username: null
  password: null

dirs: 
  tmp_code_dir: /tmp
  
minio:
  url: minio:9000
  key: 
  secret:

smtp:
  host: 
  port: 
  
emails:
  noreply:
    addr:
    password: