server:
  host:
  port:
  
database:
  db:
  host:
  port:
  username: 
  password:

minio:
  url:
  key:
  secret:

jwt-secret:
session-secret:

smtp:
  host: 
  port: 
  
emails:
  noreply:
    addr:
    password: 

sandbox:
  user:
  image: 
  workdir: 
  mounts:
  mem_limit: