server:
  host: 
  port: 

database:
  db: 
  host: 
  port:
  username: null
  password: null

dirs:
  USERS_TMP_CODE_DIR: 
  TESTSUITES_ATTACHMENTS:
  USERS_PROFILE_PHOTOS_DIR:

jwt-secret: 
session-secret: 

smtp:
  host: 
  port: 
  
emails:
  noreply:
    addr:
    password: 

sandbox:
  user: 
  image: 
  workdir: 
  mounts: 
  mem_limit:
