server:
  host: 0.0.0.0 
  port: 5000
  
database:
  db: 
  host: 
  port: 
  username: null
  password: null

dirs: 
  tmp_code_dir:
  
minio:
  url: 
  key: 
  secret: 

jwt-secret:
session-secret: 

smtp:
  host: 
  port: 
  
emails:
  noreply:
    addr:
    password: 
