version: '2'
services:
  mongodb:
    restart: always
    image: mongo:3.4
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /data/db:/data/db
    ports:
        - 2000:2000
    command: mongod --port 2000 --smallfiles --logpath=/dev/null

  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    links:
      - flaskapp:uwsgi
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf