languages:

  cpp_98:
    title: C++
    docker-image: gcc:4.9
    compiler:
      cmd: g++ -w -fmessage-length=10000 -fno-diagnostics-show-caret -std=c++98 {source_file} -o output.out
    executer:
      cmd: ./output.out {stdin}
    extensions:
      - .C
      - .cc
      - .cpp, 
      - .CPP
      - .c++
      - .cp
      - .cxx

  cpp_11:
    title: C++
    docker-image: gcc:4.9
    compiler:
      cmd: g++ -w -fmessage-length=10000 -fno-diagnostics-show-caret -std=c++11 {source_file} -o output.out
    executer:
      cmd: ./output.out {stdin}
    extensions:
      - .C
      - .cc
      - .cpp, 
      - .CPP
      - .c++
      - .cp
      - .cxx

  cpp_14:
    title: C++
    docker-image: gcc:4.9
    compiler:
      cmd: g++ -w -fmessage-length=10000 -fno-diagnostics-show-caret -std=c++14 {source_file} -o output.out
    executer:
      cmd: ./output.out {stdin}
    extensions:
      - .C
      - .cc
      - .cpp, 
      - .CPP
      - .c++
      - .cp
      - .cxx